### PR TITLE
updating jquery.ui.pos to v1.12.1

### PR DESCRIPTION
**Pull request by chenzhenhu**
There will be errors when using jQuery3: Uncaught TypeError: f.getClientRects is not a function

### CODE REVIEW

**Comment by itsjavi** [comment]
Thanks for your PR, I added you as a contributor of the project.
Please remember to follow the guidelines of `CONTRIBUTING.md` before merging. The `dist` files should be also updated by generating them using `grunt`.

**Comment by thomas-rolling** [comment]
Same issue as here https://github.com/farbelous/fontawesome-iconpicker/issues/52

This PR solve my problem (after run grunt command of course). 

Please finish this PR and merge it!

**Comment by thomas-rolling** [comment]
You rock 👍

**Comment by thomas-rolling** [comment]
Update `package.json` for Yarn ?

**Pull request closed without merging**
