### PR TITLE
Minor css changes

### PR DESCRIPTION
**Pull request by ralphonz**
-added background color to selected icon as otherwise its white on white
-added z-index to popover to ensure it appears on top of existing elements

### CODE REVIEW

**Comment by itsjavi** [comment]
Thanks for your PR, I added you as a contributor of the project.
Please remember to follow the guidelines of CONTRIBUTING.md before merging. The dist files should be also updated by generating them using grunt.

**Comment by ralphonz** [comment]
Thanks.  I'm new to collaborating on GitHub so bear with me.  I've installed bower, npm and ran grunt and committed the changes.  Whats next?

**Comment by itsjavi** [comment]
did you run grunt inside the project folder? I don't see the updated dist/*.css files

**Comment by itsjavi** [comment]
I think you commited all your `bower_components` files 😅

**Comment by ralphonz** [comment]
Sorry about that, is that any better?  It picked up changes to `bower_components` because I previously didn't have it installed.

**Comment by itsjavi** [comment]
better, thank you

**Pull request merged**
